version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of your requirements.txt file
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
